CREATE DATABASE note_app CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE note_app;

CREATE TABLE notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
